---

Battle: &battles
- !<battle> {name: Nagato, order: 1}
- !<battle> {name: Shikoku, order: 2}

Clan:
- &Koi !<clan> {type: Koi, coins: 10}
- &Fox !<clan> {type: Fox, coins: 3}
- &Dragonfly !<clan> {type: &Dragonfly, conins: 6}
